language: go

go:
- 1.7rc3

sudo: required
dist: trusty

services:
- docker

before_install:
- curl -L https://github.com/Masterminds/glide/releases/download/0.10.2/glide-0.10.2-linux-amd64.zip
  > glide.zip
- unzip glide.zip
- export PATH="$PATH:$PWD/linux-amd64"
- go get -u github.com/golang/lint/golint

script:
- make deps
- make
